### ISSUE TITLE
The sample don't working at node 7.3.0

### ISSUE THREAD

**Issue by gmamaral** [evidenceprime/html-docx-js-node-sample#3]
binding.open(pathModule._makeLong(path),
          ^

TypeError: path must be a string or Buffer
    at Object.fs.readFile (fs.js:273:11)
    at Object.<anonymous> (D:\Users\admin\Desktop\html-docx-js-node-sample-master\index.js:7:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)

**Comment by kyryloholodnov** [comment]
@gmamaral You probably should pass input file and output file as params to node.
Something like this:
`node index.js input.html output.docx`
This works on node v8.9.4.

**Comment by OctoberCity** [comment]
@gmamaral Are you successful, I am able to execute but cannot export pictures

**Comment by abhinovpankaj** [comment]
Getting below error on Node v18.16.0

Error is TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Blob
